spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.initialization-mode=always
spring.datasource.url=jdbc:postgresql://77.91.84.45:5432/skypro_tg
spring.datasource.username=user
spring.datasource.password=password

bot.name = Asha
bot.key = 6162958373:AAF4Vaqz4K1CfEDsVzF4PwxJb26fTGMq6hg

